### ISSUE TITLE
Install firewall

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/mac-linux-gaming-stick#103]
Install a firewall that also has a nice GUI.

**Comment by ekultails** [comment]
Option 1: Uncomplicated Firewall (UFW). Install `ufw` (CLI) and `gufw` (GUI).
Option 2: Firewalld. Install `firewalld` which includes both the `firewall-cmd` (CLI) and `firewall-config` (GUI) programs.
