### ISSUE TITLE
Use LUKS encryption

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/mac-linux-gaming-stick#55]
Related to this change, password changes should be enforced. These passwords should be changed on first boot:

1. `root` user.
2. `stick` user.
3. LUKS encryption password.

**Comment by ekultails** [comment]
This brings up a related question: do we want to ship two different images? A "performance" (security workarounds disabled in kernel, no LUKS encryption, etc.) and a "security" image?

**Comment by ekultails** [comment]
Storage encryption provides a 4% increase in CPU usage: https://www.phoronix.com/scan.php?page=article&item=ubuntu-1804-encrypt&num=5

**Comment by LukeShortCloud** [comment]
How to create a LUKS encrypted partition:

https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system

How to resize a LUKS encrypted partition:

https://unix.stackexchange.com/questions/320957/extend-a-luks-encrypted-partition-to-fill-disk/548319

How to increase LUKS encryption password:

https://unix.stackexchange.com/questions/252672/how-do-i-change-a-luks-password

**Comment by LukeShortCloud** [comment]
I ran into some issues using the UUID of the `/dev/vda4` partition. Next up to try is to use a label instead: https://unix.stackexchange.com/questions/470665/how-to-specify-cryptdevice-by-label-using-systemd-boot

**Comment by LukeShortCloud** [comment]
Labels example:

```
$ sudo cryptsetup config --label=cryptroot /dev/vda4
```

Then set the kernel cmdline options to include `cryptdevice=LABEL=cryptroot`.

**Comment by LukeShortCloud** [comment]
GRUB also needs to be configured to boot with LUKS encryption since it is part of the root partition on `/dev/vda4`.

```
$ sudo vim /mnt/etc/default/grub
GRUB_ENABLE_CRYPTODISK=y
```

https://wiki.archlinux.org/title/Dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_(GRUB)

**Comment by LukeShortCloud** [comment]
It would be a lot easier to put `/boot/` on an unencrypted partition.

**Comment by LukeShortCloud** [comment]
It is important to note that I tested labels as an alternative to UUIDs. It did not fix the issue but was cleaner and easier to work with so we probably switch to labels.

The underlying issue may be a misconfiguration in `/mnt/etc/crypttab` (we currently do not modify it).

**Comment by LukeShortCloud** [comment]
Use `GRUB_CMDLINE_LINUX` and NOT `GRUB_CMDLINE_LINUX_DEFAULT` in `/mnt/etc/default/grub.cfg`. Otherwise, GRUB will automatically generate the UUID of the root partition that is mounted (which will NOT be found since it will be encrypted on boot) as a /proc/cmdline argument of "root=UUID=<UNENCRYPTED_UUID>" and will complain about it not existing on boot.

https://bbs.archlinux.org/viewtopic.php?id=247333

**Comment by LukeShortCloud** [comment]
We need to document to users that (1) they should add their own LUKS key and (2) remove the "password" LUKS key immediately.

**Comment by LukeShortCloud** [comment]
Also add notes to the CHANGELOG.md file.
